# Generated by Django 4.2 on 2023-08-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_nip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niprecord',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='niprecord',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='niprecord',
            name='reservation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='niprecord',
            name='nip',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='niprecord',
            name='status',
            field=models.CharField(choices=[('ZAREZERWOWANY', 'Zarezerwowany'), ('REZERWACJA WYGASŁA', 'Rezerwacja wygasła'), ('DOSTĘPNY', 'Dostępny')], max_length=20),
        ),
    ]
