# Generated by Django 4.2 on 2023-08-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_nip_app', '0002_niprecord_email_niprecord_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niprecord',
            name='status',
        ),
    ]
