# Generated by Django 4.2 on 2023-09-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_nip_app', '0004_alter_niprecord_nip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
