# Generated by Django 4.2 on 2023-09-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_nip_app', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
