# Generated by Django 4.2 on 2023-09-07 21:41

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_nip_app', '0006_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niprecord',
            name='email',
        ),
        migrations.RemoveField(
            model_name='niprecord',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='niprecord',
            name='reservation_date',
        ),
        migrations.AddField(
            model_name='niprecord',
            name='data_koncowa',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 21, 41, 31, 465440, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='niprecord',
            name='data_poczatkowa',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='niprecord',
            name='email_klienta',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='niprecord',
            name='nazwa',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='niprecord',
            name='numer_telefonu_klienta',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='niprecord',
            name='status',
            field=models.CharField(choices=[('ZABLOKOWANY', 'Zablokowany'), ('WOLNY DO REZERWACJI', 'Wolny do rezerwacji')], default='WOLNY DO REZERWACJI', max_length=20),
        ),
        migrations.AlterField(
            model_name='niprecord',
            name='nip',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
