# Generated by Django 4.2 on 2023-09-07 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_nip_app', '0007_remove_niprecord_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niprecord',
            name='data_koncowa',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 22, 49, 52, 135451, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='niprecord',
            name='nip',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
