# Generated by Django 4.0.6 on 2023-09-21 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_nip_app', '0008_alter_niprecord_data_koncowa_alter_niprecord_nip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niprecord',
            old_name='email_klienta',
            new_name='email_uzytkownika',
        ),
        migrations.AlterField(
            model_name='niprecord',
            name='data_koncowa',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 12, 2, 35, 110797, tzinfo=utc)),
        ),
    ]
