# Generated by Django 4.0.6 on 2023-12-01 22:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_nip_app', '0010_alter_niprecord_data_koncowa_alter_niprecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niprecord',
            name='data_koncowa',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 22, 27, 30, 754584, tzinfo=utc)),
        ),
    ]
