# Generated by Django 4.0.6 on 2023-12-02 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacja_nip_app', '0011_alter_niprecord_data_koncowa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niprecord',
            name='data_koncowa',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 10, 46, 37, 927662, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='niprecord',
            name='nazwa',
            field=models.CharField(max_length=255),
        ),
    ]
