# Generated by Django 4.2.8 on 2023-12-16 09:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rezerwacja_nip_app", "0014_alter_niprecord_data_koncowa"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaddress",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="niprecord",
            name="data_koncowa",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 14, 9, 23, 23, 497913, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
