# Generated by Django 4.2.8 on 2023-12-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rezerwacja_nip_app", "0015_emailaddress_user_alter_niprecord_data_koncowa"),
    ]

    operations = []
