# Generated by Django 4.2.8 on 2023-12-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezerwacja_nip_app", "0018_alter_niprecord_data_koncowa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiration_days", models.IntegerField(default=60)),
            ],
        ),
        migrations.AlterField(
            model_name="niprecord",
            name="data_koncowa",
            field=models.DateTimeField(),
        ),
    ]
