# Generated by Django 4.2.8 on 2024-01-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rezerwacja_nip_app", "0020_remove_administrator_nip_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="niprecord",
            name="nip",
        ),
    ]
