# Generated by Django 4.2.8 on 2024-01-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezerwacja_nip_app", "0021_remove_niprecord_nip"),
    ]

    operations = [
        migrations.AddField(
            model_name="niprecord",
            name="nip",
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
