# Generated by Django 4.2.8 on 2024-01-04 23:47

from django.db import migrations
from django.db import models
from django.utils import timezone
from rezerwacja_nip_app.models import Settings


class Migration(migrations.Migration):

    dependencies = [
        ("rezerwacja_nip_app", "0023_alter_niprecord_nip"),
    ]

    operations = [
        migrations.AddField(
            model_name='niprecord',
            name='nip',
            field=models.CharField(max_length=10, unique=False),
        ),
    ]

