# Generated by Django 4.2.8 on 2024-01-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezerwacja_nip_app", "0025_alter_niprecord_nip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="niprecord",
            name="nip",
            field=models.CharField(max_length=10),
        ),
    ]
