# Generated by Django 4.2.8 on 2024-01-25 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezerwacja_nip_app", "0026_alter_niprecord_nip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="niprecord",
            name="nip",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1000000000, message="NIP must be a 10-digit number."
                    ),
                    django.core.validators.MaxValueValidator(
                        9999999999, message="NIP must be a 10-digit number."
                    ),
                ],
            ),
        ),
    ]
